name: rounds
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"
#form 7 to 11 2.7.0
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^3.0.0
  dio: ^3.0.10
  intl: ^0.16.1
  ntp: ^1.0.6
  shared_preferences: ^0.5.8
  connectivity: ^3.0.3
  cached_network_image: ^2.2.0+1
  file_picker: ^2.0.0
  video_player: ^2.0.2
  share: ^0.6.5+3
  image_cropper : ^1.3.1
  chewie: ^1.0.0
  audioplayers: ^0.16.2
  multi_image_picker: ^4.7.14
  path_provider: ^1.6.24
  flutter_share: ^1.0.5
  percent_indicator: ^2.1.9
  mailer: ^3.2.1
  open_file: ^3.0.3
  flutter_easyloading: ^2.2.1
  firebase_core_web: ^0.2.1+2
  image_picker: ^0.6.7+22
  flutter_form_builder: ^3.14.1
  intent: ^1.4.0
  photo_view: ^0.10.3
  http: ^0.12.2
  wc_flutter_share: ^0.2.0
  fluttertoast: ^4.0.1
  flutter_audio_recorder: ^0.5.2
  speech_to_text: ^3.1.0
  localstorage: ^3.0.6+9
  firebase_core: ^0.7.0
  firebase_database: ^6.0.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0
  animated_splash_screen: ^1.0.1+2
  printing: ^4.1.0
  flutter_slidable: ^0.5.7
  dropdown_button2: ^1.4.0
  permission_handler: ^5.1.0+2
  flutter_absolute_path: ^1.0.6
  flutter_launcher_icons:
  smooth_page_indicator: ^1.0.0+2
  pinch_zoom: ^1.0.0
  flutter_cached_pdfview: ^0.3.5
  introduction_screen: ^1.0.8
  flutter_local_notifications: ^4.0.1+2
  contacts_service: ^0.4.6
  url_launcher: ^5.7.8





  #flutter_offline: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "images/logo2.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/
    - images/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: images/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: images/fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: images/fonts/Poppins-Regular.ttf
